### ISSUE TITLE
Error installing theme-bootstrap

### ISSUE THREAD

**Issue by danimog** [oruga-ui/theme-bootstrap#9]
yarn add @oruga-ui/theme-bootstrap
yarn add v1.22.19
warning ../../../package.json: No license field
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@oruga-ui%2ftheme-bootstrap: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/danielemoggia/DEVELOP/Oruga/test-oruga/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by jtommy** [comment]
It has not been released yet, you can use it only using the current dev branch

**Comment by jtommy** [comment]
@danimog just released!
